---
title: "来店解析 : no_profile_20200330.csv"
subtitle: "来店確率解析, CART、RF利用変数リスト、R sample コード "
author: "滋賀大学 佐藤、李"
# date: "最終更新: `r format(Sys.time(), '%Y/%m/%d')`"
date: "最終更新: 2020/9/24 向け"

output:
  # word_document:
  html_document:
  # html_notebook:
   number_section: true
   toc: true
   code_folding: hide
   toc_float:
     smooth_scroll: false
     collapsed: false
  # fig_width: 18
  # fig_height: 12
---

# install pkg and smbc pkg version
```{r}
# install.packages("./SMBC202006Pkg/", repos = NULL, type = "source")
library(SMBC202006Pkg)
suppressMessages(library(party))
suppressMessages(library(tidyverse))
suppressMessages(library(pROC))
packageVersion("SMBC202006Pkg")
```

# 変数リスト

## 分析に利用した変数（英語変数名）

```{r}
d <-  SMBC202006Pkg::d1.rf 
# %>% select(
# -Num_of_months_since_the_last_visit,
# -Num_of_visits_past_3_months,
# -Num_of_visits_last_6_months,
# -Num_of_visits_last_12_months,
# # -Num_of_visits_past_3_years,
# -Num_of_visits_during_the_whole_period
# )

d$num_br <- as.factor(d$num_br)
d$info_job <- as.factor(d$info_job)

use.var.name.E<-d %>% colnames() %>% data.frame(use.var.name.E=.)

# use.var.name.E %>% DT::datatable()
# 
# 
# head(use.var.name.E)
```

## 変数名、和英対応表
```{r}
var.name.list <- SMBC202006Pkg::var_jpn %>%
  bind_cols(., Eng = SMBC202006Pkg::var_eng$Eng)
  
var.name.list$Eng <- var.name.list$Eng %>% as.character()
var.name.list %>% DT::datatable()
```

## 分析に利用した変数の和英対応表
- **`分析に利用した変数の和英対応表.csv`**参考
```{r}
use.var.list.EJ<-left_join(use.var.name.E ,var.name.list , 
          by=c("use.var.name.E"="Eng")) 

# use.var.list.EJ%>% write.csv("bb.csv")

use.var.list.EJ %>% DT::datatable()

# full_join(var.name.list,use.var.name.E,
#                            by=c("Eng"="use.var.name.E")) %>% DT::datatable()
```


# 実装コード
## data 読み込みと点番号、職業コード因子型変換
- final data name : `d`

```{r, eval=F, echo=T}
d <- read.csv("CSV file 名", header = T)
d$num_br <- as.factor(d$num_br)
d$info_job <- as.factor(d$info_job)
```


<!-- ```{r} -->
<!-- d <- -->
<!-- SMBC202006Pkg::d1.rf  -->
<!-- # %>% select( -->
<!-- # -Num_of_months_since_the_last_visit, -->
<!-- # -Num_of_visits_past_3_months, -->
<!-- # -Num_of_visits_last_6_months, -->
<!-- # -Num_of_visits_last_12_months, -->
<!-- # # -Num_of_visits_past_3_years, -->
<!-- # -Num_of_visits_during_the_whole_period -->
<!-- # ) -->

<!-- d$num_br <- as.factor(d$num_br) -->
<!-- d$info_job <- as.factor(d$info_job) -->
<!-- ``` -->

<!-- ## data dimension and overall structure -->
<!-- ```{r} -->
<!-- dim(d) -->
<!-- d %>% head() %>% DT::datatable() -->
<!-- ``` -->


## CART R code
### cart total and predict value
```{r, eval=F}
library(party)
cart.total <- ctree(y_binary ~ ., data = d)
cart.total

# or  ctree_controlのoption 指定
# 例）
# cart.total <- ctree(y_binary ~ .,
#                     data = d,
#                     controls = ctree_control(minsplit = 数値を指定))


cart.total.predicted <-
predict(cart.total, type = "prob") %>%
purrr::map_dbl(.x = . , function(x) {
x[2]
})

# 実測、予測ペアー
Roc.total <-
cbind(y = as.numeric(d$y_binary) - 1, cart.total.predicted) 
```


## RF R code

```{r, eval=F}
library(randomForest)
rf.total <- randomForest(y_binary ~ ., data = d, method = "class")
rf.total$confusion
pred.rf <- cbind(y = as.numeric(d$y_binary) - 1,
predict(rf.total, newdata = d, type = "prob"))

# 実測、予測ペアー
pred.rf1 
```

<!-- ## predicted value - cart -->

<!-- ```{r} -->

<!-- cart.total <- ctree(y_binary ~ ., data = d, -->
<!--                     controls = ctree_control(minsplit = 10 ^ 4 + 10 ^ 4 / 2)) -->
<!-- cart.total -->


<!-- cart.total.predicted <- -->
<!--   predict(cart.total, type = "prob") %>% -->
<!--   purrr::map_dbl(.x = . , function(x) { -->
<!--     x[2] -->
<!--   }) %>% tbl_df() -->

<!-- Roc.total <- cbind(y=as.numeric(d$y_binary)-1, cart.total.predicted) %>% tbl_df() -->
<!-- ``` -->

<!-- - 全店舗 -->
<!-- ```{r, warning=F} -->
<!-- Roc.total %>% round(2) %>% DT::datatable() -->
<!-- ``` -->

<!-- # RF-来店確率 -->

<!-- ```{r} -->
<!-- suppressMessages(library(randomForest)) -->
<!-- # rf.total <- randomForest(y_binary ~ ., data = d, method = "class") -->
<!-- # save.image("rf10.Rdata") -->

<!-- # load("rf10.Rdata") -->


<!-- rf.total<-SMBC202006Pkg::rf.total -->

<!-- rf.total$confusion -->
<!-- # rf.total$err.rate -->


<!-- pred.rf<-cbind(y=as.numeric(d$y_binary)-1, -->
<!-- predict(rf.total, newdata = d, type = "prob") -->
<!-- )  -->

<!-- pred.rf %>% DT::datatable() -->

<!-- ``` -->

## 予測値をcsvファイルへ保存
```{r, eval=F}
# CART
write.csv(Roc.total, "file名.csv")

# RF 
write.csv(data.frame(pred.rf), "file名.csv")
```


<!-- ## result of AUC -->
<!-- ```{r} -->

<!-- a<-roc( -->
<!--   Roc.total$y~Roc.total$value, -->
<!--   plot = F, -->
<!--   print.auc = T, -->
<!--   col = "red", -->
<!--   # add = T, -->
<!--   print.auc.y = 0.6, -->
<!--   print.auc.x = 1/2 -->
<!-- ) -->



<!-- b<-roc( -->
<!--   Roc.Fukuoka$y~Roc.Fukuoka$value, -->
<!--   plot = F, -->
<!--   print.auc = T, -->
<!--   col = "red", -->
<!--   add = T, -->
<!--   print.auc.y = 0.6, -->
<!--   print.auc.x = 1/2 -->
<!-- )  -->


<!-- c<-roc( -->
<!--   Roc.Sapporo$y~Roc.Sapporo$value, -->
<!--   plot = F, -->
<!--   print.auc = T, -->
<!--   col = "red", -->
<!--   add = T, -->
<!--   print.auc.y = 0.6, -->
<!--   print.auc.x = 1/2 -->
<!-- )  -->



<!-- cbind(全店舗=a$auc, 福岡=b$auc,札幌=c$auc) -->

<!-- ``` -->


<!-- ## comparison of ROCs -->
<!-- ```{r} -->
<!-- col<- c("red", "green",  "blue") -->


<!-- par(family= "HiraKakuProN-W3") -->

<!-- roc( -->
<!--   Roc.total$y~Roc.total$value, -->
<!--   plot = F, -->
<!--   print.auc = T, -->
<!--   col = "red", -->
<!--   # add = T, -->
<!--   print.auc.y = 0.6, -->
<!--   print.auc.x = 1/2 -->
<!-- ) %>% plot(col=col[1]) -->


<!-- roc( -->
<!--   Roc.Fukuoka$y~Roc.Fukuoka$value, -->
<!--   plot = F, -->
<!--   print.auc = T, -->
<!--   col = "red", -->
<!--   add = T, -->
<!--   print.auc.y = 0.6, -->
<!--   print.auc.x = 1/2 -->
<!-- ) %>% plot(add=T, col=col[2]) -->


<!-- roc( -->
<!--   Roc.Sapporo$y~Roc.Sapporo$value, -->
<!--   plot = F, -->
<!--   print.auc = T, -->
<!--   col = "red", -->
<!--   add = T, -->
<!--   print.auc.y = 0.6, -->
<!--   print.auc.x = 1/2 -->
<!-- ) %>% plot(add=T, col=col[3]) -->


<!-- legend("bottomright", -->
<!--   legend = c( -->
<!--     "全店舗", -->
<!--     "福岡", -->
<!--     "札幌" -->
<!--   ), -->
<!--   col = c("red", "green", "blue"), -->
<!--   lwd = 4 -->
<!-- ) -->

<!-- ``` -->

